[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "chainlit run app.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
