services:
  - type: web
    name: careerpath-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
